[project]
name = "skale-proxy"
version = "2.2.0"
requires-python = ">=3.13"
dependencies = [
    "web3==7.14.0",
    "Jinja2==3.1.6",
    "colorful==0.5.8",
    "docker==7.1.0",
    "requests==2.32.5",
]

[project.optional-dependencies]
dev = ["ruff==0.14.3", "mypy==1.18.2"]

[tool.uv]
prerelease = "allow"

[tool.pytest.ini_options]
log_cli = false
log_cli_level = "INFO"
log_cli_format = "[%(asctime)s] [%(levelname)8s] [%(threadName)s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = ["ignore::DeprecationWarning"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "W", "F", "I"]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
ignore_missing_imports = true
