name: Test proxy
on: [push, pull_request]

jobs:
  test_proxy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MANAGER_TAG: "1.9.3-beta.0"
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python 3.13
        run: uv python install 3.13
      - name: Install python dependencies
        run: uv sync --all-extras
      - name: Lint with ruff
        run: uv run ruff check proxy/
