[project]
name = "skale-metrics"
version = "2.2.0"
requires-python = ">=3.13"
dependencies = [
    "web3==7.14.0",
    "requests==2.32.5",
    "aiohttp==3.13.2",
    "peewee==3.18.3",
    "PyMySQL==1.1.2",
    "cryptography==46.0.3",
]

[project.optional-dependencies]
dev = [
    "ruff==0.14.3",
    "pytest==8.4.2",
    "pytest-asyncio==0.25.2",
    "Faker==37.12.0",
    "pytest-aiohttp==1.1.0",
    "eth-typing==5.2.1",
    "eth-utils==5.3.1",
    "types-peewee==3.18.2.20250710",
]

[tool.uv]
prerelease = "allow"

[tool.pytest.ini_options]
log_cli = false
log_cli_level = "INFO"
log_cli_format = "[%(asctime)s] [%(levelname)8s] [%(threadName)s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = ["ignore::DeprecationWarning"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "W", "F", "I"]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
ignore_missing_imports = true
